// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsVf0an5zJCMrCFa0_ORjTipUJoptqJUc',
    appId: '1:1012204243775:web:308b64d7ec63cca79fa18a',
    messagingSenderId: '1012204243775',
    projectId: 'suits-d4a64',
    authDomain: 'suits-d4a64.firebaseapp.com',
    storageBucket: 'suits-d4a64.firebasestorage.app',
    measurementId: 'G-H9XTPNF44N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB80oMMqepsM0THIlTLI872qz-km8PN07I',
    appId: '1:1012204243775:android:10a1e9f8d7c5d3c39fa18a',
    messagingSenderId: '1012204243775',
    projectId: 'suits-d4a64',
    storageBucket: 'suits-d4a64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1bGX6APRl1RrQ4GdZw9N3ZeCd65bG86o',
    appId: '1:1012204243775:ios:c3964f7c39f83ccd9fa18a',
    messagingSenderId: '1012204243775',
    projectId: 'suits-d4a64',
    storageBucket: 'suits-d4a64.firebasestorage.app',
    androidClientId:
        '1012204243775-j8jdjds04jkib4do004o5b90q8qofhnv.apps.googleusercontent.com',
    iosClientId:
        '1012204243775-dmcdhaigf3v0279fg4ju7h6i7m4nqqe5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tallyIslamic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1bGX6APRl1RrQ4GdZw9N3ZeCd65bG86o',
    appId: '1:1012204243775:ios:c3964f7c39f83ccd9fa18a',
    messagingSenderId: '1012204243775',
    projectId: 'suits-d4a64',
    storageBucket: 'suits-d4a64.firebasestorage.app',
    androidClientId:
        '1012204243775-j8jdjds04jkib4do004o5b90q8qofhnv.apps.googleusercontent.com',
    iosClientId:
        '1012204243775-dmcdhaigf3v0279fg4ju7h6i7m4nqqe5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tallyIslamic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKrO11j1xuB9OgTAEliNG5pLS0McrqKXE',
    appId: '1:1012204243775:web:76936ea5443ad6479fa18a',
    messagingSenderId: '1012204243775',
    projectId: 'suits-d4a64',
    authDomain: 'suits-d4a64.firebaseapp.com',
    storageBucket: 'suits-d4a64.firebasestorage.app',
    measurementId: 'G-XL4TE0XK3W',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDKrO11j1xuB9OgTAEliNG5pLS0McrqKXE',
    appId: '1:1012204243775:web:76936ea5443ad6479fa18a',
    messagingSenderId: '1012204243775',
    projectId: 'suits-d4a64',
    authDomain: 'suits-d4a64.firebaseapp.com',
    storageBucket: 'suits-d4a64.firebasestorage.app',
    measurementId: 'G-XL4TE0XK3W',
  );
}
